# SPDX-FileCopyrightText: 2023 Linutronix GmbH
# SPDX-License-Identifier: 0BSD

name: REUSE Compliance
on: [push]
jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: reuse
      - name: Run reuse
        run: reuse lint
